dist: trusty
language: node_js
sudo: required
branches:
  only:
  - master
  - develop
  - /^feature\/.*/
  - /^release-.*/
notifications:
  email:
    recipients:
      - ci.report@ost.com
    on_success: always
    on_failure: always
node_js:
  - "8"
before_install:
  - sudo apt-get update
  - sudo apt-get install nodejs
  - sudo apt-get install npm
install:
  - npm install
before_script:
script:
after_script:
